server:
  port: 10002
logging:
  config: classpath:logback-spring.xml
  path: /mnt/tuodao_api/cloud-manage-api/log
  level: 
        com.whb.aop: debug,
        com.whb.io: debug
spring: 
  dubbo:
    scan: com.whb.aop
    application:
      name: whb-server
      owner: tuodao
    registry:
      address: zookeeper://114.55.30.32:2181
      group: whb
    protocol:
          name: dubbo
          port: 20880
    provider:
      timeout: 60000
      retries: -1
  redis:
    cluster:
      nodes:
        - 114.55.30.32:34587
        - 114.55.30.32:34588
        - 114.55.30.32:34589
        - 114.55.30.32:34590
        - 114.55.30.32:34591
        - 114.55.30.32:34592
    database: 1
    pool:
      max-wait: 50
  
  sleuth:
    enabled: true
    sampler:
      percentage: 1

  aop:
    auto: true
    proxy-target-class: true
      
############################################################################
### 这里使用cron表达式来定时                                             ###
### 以下为cron表达式每一位说明                                           ###
### 1.        Seconds                                                    ###
### 2.        Minutes                                                    ###
### 3.        Hours                                                      ###
### 4.        Day-of-Month                                               ###
### 5.        Month                                                      ###
### 6.        Day-of-Week                                                ###
### 7.        Year (可选字段)                                            ###
### "*"代表整个时间段                                                    ###
### "?"字符：表示不确定的值                                              ###
### ","字符：指定数个值                                                  ###
### "-"字符：指定一个值的范围                                            ###
### "/"字符：指定一个值的增加幅度。n/m表示从n开始，每次增加m             ###
### "L"字符：用在日表示一个月中的最后一天，用在周表示该月最后一个星期X   ###
### "W"字符：指定离给定日期最近的工作日(周一到周五)                      ###
### "#"字符：表示该月第几个周X。6#3表示该月第3个周五                     ###
############################################################################
schedule:
  # 文件上传定时任务启动时间(每天凌晨0点10分时执行)
  fileUpLoadOss:  0 10 0 * * ?
  # 超时未处理逾期减免打回定时任务启动时间(每天凌晨0点5分时执行)
  autoBackOverdueReliefInfo:  0 5 0 * * ?
  # 业务员业绩定时任务时间(每天凌晨0点30分时执行)
  autoCreateAchievementInfoTask: 0 30 0 * * ?
  # 车300汽车信息定时任务时间(每天凌晨2点执行)
  autoUpdateCarInfoTask: 0 0 2 * * ?
