server:
  port: 10009
logging:
  config: classpath:logback-spring.xml
  path: /mnt/tuodao_api/cloud-manage-api/log
  level: 
        com.whb.aop: debug,
        com.whb.io: debug
spring: 
  dubbo:
    scan: com.whb.dubbo
    application:
      name: whb-server
      owner: whb
    registry:
      address: zookeeper://114.55.30.32:2181
      group: whb
    protocol:
          name: dubbo
          port: 20880
    provider:
      timeout: 60000
      retries: -1
  redis:
    cluster:
      nodes:
        - 114.55.30.32:34587
        - 114.55.30.32:34588
        - 114.55.30.32:34589
        - 114.55.30.32:34590
        - 114.55.30.32:34591
        - 114.55.30.32:34592
    database: 1
    pool:
      max-wait: 50
  
  sleuth:
    enabled: true
    sampler:
      percentage: 1

  aop:
    auto: true
    proxy-target-class: true
    
##redisson分布式锁
dislock:
  redisson:
    startup: true
    clusterServersConfig:
      idleConnectionTimeout: 10000
      pingTimeout: 1000
      connectTimeout: 10000
      timeout: 3000
      retryAttempts: 3
      retryInterval: 1500
      reconnectionTimeout: 3000
      failedAttempts: 3
      #password: null
      subscriptionsPerConnection: 5
      clientName: null
      #loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
      slaveSubscriptionConnectionMinimumIdleSize: 1
      slaveSubscriptionConnectionPoolSize: 50
      slaveConnectionMinimumIdleSize: 10
      slaveConnectionPoolSize: 64
      masterConnectionMinimumIdleSize: 10
      masterConnectionPoolSize: 64
      readMode: "SLAVE"
      nodeAddresses:
      - "redis://114.55.30.32:34587"
      - "redis://114.55.30.32:34588"
      - "redis://114.55.30.32:34589"
      - "redis://114.55.30.32:34590"
      - "redis://114.55.30.32:34591"
      - "redis://114.55.30.32:34592"
      scanInterval: 1000    
 
      

##数据库
hikari:
  type: com.zaxxer.hikari.HikariDataSource
  master:
    jdbc-url: jdbc:mysql://72.127.2.158:3306/finance?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tuodao_mysql
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 30
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000
      idle-timeout: 60000
  slave1:
    jdbc-url: jdbc:mysql://72.127.2.158:3306/finance?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tuodao_mysql
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 30
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000
      idle-timeout: 60000
  slave2:
    jdbc-url: jdbc:mysql://72.127.2.158:3306/finance?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tuodao_mysql
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 30
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000
      idle-timeout: 60000      

##mapper映射路径
mybatis:
  mapper-locations: classpath*:xml/**/*Mapper.xml

############################################################################
### 这里使用cron表达式来定时                                             ###
### 以下为cron表达式每一位说明                                           ###
### 1.        Seconds                                                    ###
### 2.        Minutes                                                    ###
### 3.        Hours                                                      ###
### 4.        Day-of-Month                                               ###
### 5.        Month                                                      ###
### 6.        Day-of-Week                                                ###
### 7.        Year (可选字段)                                            ###
### "*"代表整个时间段                                                    ###
### "?"字符：表示不确定的值                                              ###
### ","字符：指定数个值                                                  ###
### "-"字符：指定一个值的范围                                            ###
### "/"字符：指定一个值的增加幅度。n/m表示从n开始，每次增加m             ###
### "L"字符：用在日表示一个月中的最后一天，用在周表示该月最后一个星期X   ###
### "W"字符：指定离给定日期最近的工作日(周一到周五)                      ###
### "#"字符：表示该月第几个周X。6#3表示该月第3个周五                     ###
############################################################################
schedule:
  # 文件上传定时任务启动时间(每天凌晨0点10分时执行)
  fileUpLoadOss:  0 10 0 * * ?
  # 超时未处理逾期减免打回定时任务启动时间(每天凌晨0点5分时执行)
  autoBackOverdueReliefInfo:  0 5 0 * * ?
  # 业务员业绩定时任务时间(每天凌晨0点30分时执行)
  autoCreateAchievementInfoTask: 0 30 0 * * ?
  # 车300汽车信息定时任务时间(每天凌晨2点执行)
  autoUpdateCarInfoTask: 0 0 2 * * ?
